apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: helloworld
    port: 9999
    host: r3.a96b11b.kyma.shoot.live.k8s-hana.ondemand.com
  rules:
    - path: /.*
      methods: ["GET","POST","PUT","DELETE","HEAD"]
      accessStrategies:
        - handler: allow