apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  labels:
    app: python-helloworld
  name: python-helloworld
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: python-helloworld
    port: 9999
    host: helloworld.kyma.local
  rules:
    - path: /.*
      methods: ["GET","POST","PUT","DELETE","HEAD"]
      accessStrategies:
        - handler: allow