apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-helloworld
  namespace: dev 
  labels:
    app: python-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-helloworld
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      - image: shahidla/python-helloworld:v3.0.0 
        imagePullPolicy: Always
        name: python-helloworld
        ports:
        - name: http
          containerPort: 9999
        env:
        - name: DEBUG
          value: "true"
        - name: RENEWCERT_JOB_CRON
          value: "00 00 */12 * * *"
        volumeMounts:
        - mountPath: "/app/keys"
          name: python-helloworld-volume
        resources:
          requests:
            memory: "150Mi"
            cpu: "50m"
          limits:
            memory: "250Mi"
            cpu: "100m"
      volumes:
      - name: python-helloworld-volume
        persistentVolumeClaim:
          claimName: python-helloworld 
---
apiVersion: v1
kind: Service
metadata:
  name: python-helloworld
  labels:
    app: python-helloworld
spec:
  ports:
  - name: http
    port: 9999
    protocol: TCP
  selector:
    app: python-helloworld
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-helloworld
  labels:
    app: python-helloworld
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi